name: era_shop
description: A Flutter e-commerce application with live selling features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.0.3
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^6.1.1
  flutter_stripe: ^10.0.0
  razorpay_flutter: ^1.3.6
  flutterwave_standard: ^1.0.8
  image_picker: ^1.0.4
  video_player: ^2.8.6
  chewie: ^1.8.1
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1
  platform_device_id: ^1.0.0
  native_device_orientation: ^1.2.1
  flutter_local_notifications: ^16.1.0
  fluttertoast: ^8.2.2
  connectivity_plus: ^5.0.2
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  zego_express_engine: ^3.15.1+2
  socket_io_client: ^2.0.3+1
  intl: ^0.18.1
  country_picker: ^2.0.22
  syncfusion_flutter_datepicker: ^23.1.44
  cool_dropdown: ^2.1.0
  encrypt: ^5.0.3
  url_launcher: ^6.2.6
  path_provider: ^2.0.15
  vibration: ^1.9.0
  pinput: ^3.0.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Live_page_image/
    - assets/Entry_image/
    - assets/button_image/
    - assets/Home_page_image/
    - assets/bottombar_image/
    - assets/gallary_image/
    - assets/product_detail/
    - assets/product_review/
    - assets/icons/
    - assets/profile_icons/
    - assets/gif/
    - assets/lottie/
    - assets/no_data_found/
    - assets/FakeItemsForLive/
    - assets/data/